[build]
  command = "npm ci && npm run db:generate && npm run db:seed && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXTAUTH_SECRET = "demo-secret-for-netlify-build"
  DATABASE_URL = "file:./dev.db"
  NEXTAUTH_URL = "https://your-site-name.netlify.app"
  GOOGLE_PLACES_API_KEY = "AIzaSyBb-AUwxWuVsgK7FfMl4rny3LuUh-GYcOQ"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
